### ISSUE TITLE
Analogowi ludzie atakuja #1

### ISSUE THREAD

**Issue by Vonski** [QTeamTIN/-TIN-Q#3]
Czy wlasciciel kolejki powinien miec przycisk pozwalajacy na umieszczenie kogos nieuzywajacego aplikacji w kolejce?

**Comment by konradqcharczyk** [comment]
Z tego co pamiętam to rozmawialiśmy o tym, i stwierdziliśmy że takie sprawy będzie się załatwiać stopem kolejki. Ew w przyszłości mieliśmy to dodać.

**Comment by Vonski** [comment]
No myslalem o tej pauzie, ale gdyby na przyklad prowadzacy nie chcial wpuszczac do siebie analogowych bez kolejki, tylko ich wstawic na ostatnie miejsce w kolejce jak przyjda?

**Comment by konradqcharczyk** [comment]
Imo to nie będzie klikał tego przycisku stop -> skończy się kolejka -> wejdą analogowi.

**Comment by Vonski** [comment]
Mi sie wydaje, ze w szczegolnosci u nas na wydziale sa goscie ktorzy by uzywali tego przycisku. Ale mozemy to potraktowac jako feature do przetestowania jak bedzie czas, bo bez tego apka tez bedzie dzialac. Zamykam i dodaje do doca.
