### ISSUE TITLE
Oszukujacy spoznialscy

### ISSUE THREAD

**Issue by Vonski** [QTeamTIN/-TIN-Q#5]
Co robimy z sytuacja kiedy ktos klika ze jest i wchodzie, a potem nie ma go przez dlugi czas?

**Comment by konradqcharczyk** [comment]
Dwa rozwiazania mi przychodzą do głowy:
-Jakiś delikatny popup do admina że w ciagu 2minut od wyjścia poprzedniego nie ma nowego -> czekaj / wpuść następnego
- Admin odnotowuje że ktoś wszedł, jeśli między wypuszczeniem poprzedniego a wejściem nastepnego mineło 2min to alert do kolejnej osoby w kolejce żeby wpadał a spóźnialskiemu, że za późno i został przesunięty

**Comment by Vonski** [comment]
Imo, jezeli admin bedzie musial podjac decyzje jak mu ktos wejdzie, to nie bedzie tego robil i wszystko sie sypnie, ewentualnie mozna zrobic przycisk ktory dziala jak next, tylko ze nazywa sie "nie przyszedl" i wtedy traktujemy goscia jakby nie odpowiedzial. Wtedy jak admin kliknie next i gosc przyjdzie to wszystko spoko, a jak kliknie "nie przyszedl" bo goscia nie ma juz 2 minuty to tez kolejka bedzie dzialala ok, gosc nie wyleci. W taki sposob nie bedzie momentu w ktorym kolejka jest rozjebana bo ktos cos zle wyklikal.

**Comment by konradqcharczyk** [comment]
podsumuwując: 
Admin ma możliwość kliknięcia w przycisk "nie przyszedł" gdy osoba, nie wchodzi w ciągu jakiegoś czasu.
Działa to tak, jakby osoba wzywana nie odpowiedziała na alert.

**Comment by Vonski** [comment]
Dodaje do doca jako feature UIa
